/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminProductCompany;

import Business.Enterprise.Adpublisher.AdSpace;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany.Bid;
import Business.Enterprise.ProductCompany.Product;
import Business.Enterprise.ProductCompanyEnterprise;
import Business.UserAccount.Viewer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anna
 */
public class ManageBidRuleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OldManageBidRuleJPanel
     */
    private JPanel userProcessContainer;
    private ProductCompanyEnterprise productCompanyEnterprise;
    
    //private Product product;
    public ManageBidRuleJPanel(JPanel userProcessContainer, ProductCompanyEnterprise productCompanyEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productCompanyEnterprise = productCompanyEnterprise;
        
        productCompanyjTextField1.setText(productCompanyEnterprise.getName());
        popProductCom();
    }
    
    public void popProductCom(){
    productjComboBox6.removeAllItems();
     for (Product p: productCompanyEnterprise.getProductCatalog().getProductcatalog()){
         productjComboBox6.addItem(p);
     }
    }

    //Product product= (Product) productjComboBox6.getSelectedItem();
  
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        productCompanyjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productCompanyjTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        viewjButton6 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        productjComboBox6 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        femalejTextField1 = new javax.swing.JTextField();
        malejTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        primarySchooljTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        highSchooljTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bachelorjTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        masterTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        phdjTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nejTextField1 = new javax.swing.JTextField();
        sejTextField2 = new javax.swing.JTextField();
        nwjTextField3 = new javax.swing.JTextField();
        swJTextField4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        bigjTextField5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        smalljTextField6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        uljTextField7 = new javax.swing.JTextField();
        brjTextField8 = new javax.swing.JTextField();
        urjTextField9 = new javax.swing.JTextField();
        bljTextField10 = new javax.swing.JTextField();
        createRulejButton = new javax.swing.JButton();

        jLabel2.setText("Product Company");

        jLabel3.setText("Product Company");

        jLabel1.setText("Bid RULE setting");

        viewjButton6.setText("View Bid RULE");
        viewjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButton6ActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Product ");

        productjComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Viewer Gender Type");

        jLabel8.setText("Ad Space Location Type");

        jLabel5.setText("Viewer Education Type");

        jLabel7.setText("Ad Space Size Type");

        jLabel6.setText("Viewer Location Type");

        jLabel4.setText("Female");

        jLabel11.setText("Male");

        jLabel12.setText("Primary School");

        jLabel13.setText("High School");

        jLabel14.setText("Bachelor");

        jLabel15.setText("Master");

        jLabel16.setText("Phd");

        jLabel18.setText("Northeast");

        jLabel19.setText("Northswest");

        jLabel20.setText("Southeast");

        jLabel21.setText("Southwest");

        nwjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwjTextField3ActionPerformed(evt);
            }
        });

        jLabel22.setText("Big");

        jLabel23.setText("Small");

        jLabel24.setText("UpLeft");

        jLabel25.setText("UpRight");

        jLabel26.setText("BelowRight");

        jLabel27.setText("BelowLeft");

        createRulejButton.setText("Create Rule");
        createRulejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRulejButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(jLabel1)
                                    .add(122, 122, 122)
                                    .add(jLabel3)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(productCompanyjTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel10)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel4)
                                            .add(34, 34, 34)
                                            .add(femalejTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(122, 122, 122)
                                            .add(jLabel11)
                                            .add(110, 110, 110)
                                            .add(malejTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jLabel5)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel12)
                                            .add(18, 18, 18)
                                            .add(primarySchooljTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(89, 89, 89)
                                            .add(jLabel13)
                                            .add(63, 63, 63)
                                            .add(highSchooljTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel14)
                                            .add(58, 58, 58)
                                            .add(bachelorjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(89, 89, 89)
                                            .add(jLabel15)
                                            .add(97, 97, 97)
                                            .add(masterTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel16)
                                            .add(88, 88, 88)
                                            .add(phdjTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jLabel6)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel18)
                                            .add(41, 41, 41)
                                            .add(nejTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(13, 13, 13)
                                            .add(jLabel19)
                                            .add(80, 80, 80)
                                            .add(nwjTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jLabel7)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel22)
                                            .add(84, 84, 84)
                                            .add(bigjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(77, 77, 77)
                                            .add(jLabel23)
                                            .add(62, 62, 62)
                                            .add(smalljTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jLabel8)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel24)
                                            .add(62, 62, 62)
                                            .add(uljTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(87, 87, 87)
                                            .add(jLabel25)
                                            .add(56, 56, 56)
                                            .add(urjTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel27)
                                            .add(43, 43, 43)
                                            .add(bljTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(87, 87, 87)
                                            .add(jLabel26)
                                            .add(37, 37, 37)
                                            .add(brjTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel20)
                                            .add(41, 41, 41)
                                            .add(sejTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(13, 13, 13)
                                            .add(jLabel21)
                                            .add(87, 87, 87)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(createRulejButton)
                                                .add(swJTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                    .add(101, 101, 101)))
                            .add(layout.createSequentialGroup()
                                .add(jLabel9)
                                .add(31, 31, 31)
                                .add(productjComboBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(101, 101, 101)
                                .add(viewjButton6)
                                .addContainerGap())))
                    .add(layout.createSequentialGroup()
                        .add(backJButton)
                        .add(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel3)
                        .add(productCompanyjTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(productjComboBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(viewjButton6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel10)
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(femalejTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(malejTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel11))))
                .add(6, 6, 6)
                .add(jLabel5)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel12))
                    .add(primarySchooljTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(highSchooljTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(masterTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel14)
                            .add(bachelorjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel15))))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel16))
                    .add(phdjTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(jLabel6)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nejTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nwjTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel18)
                            .add(jLabel19))))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(sejTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(swJTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel20)
                            .add(jLabel21))))
                .add(12, 12, 12)
                .add(jLabel7)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bigjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(smalljTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel22)
                            .add(jLabel23))))
                .add(12, 12, 12)
                .add(jLabel8)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(uljTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(urjTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel24)
                            .add(jLabel25))))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bljTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(brjTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel27)
                            .add(jLabel26))))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(backJButton)
                    .add(createRulejButton))
                .add(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void nwjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nwjTextField3ActionPerformed

    private void viewjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButton6ActionPerformed
        // TODO add your handling code here:
        Product product = (Product) productjComboBox6.getSelectedItem();
        ViewBidRuleJPanel vbrjp = new ViewBidRuleJPanel(userProcessContainer,productCompanyEnterprise, product);
        
        userProcessContainer.add("manageOrganizationJPanel", vbrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewjButton6ActionPerformed

    private void createRulejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRulejButtonActionPerformed
        // TODO add your handling code here:
        Product  p =(Product) productjComboBox6.getSelectedItem();
      
        Bid bid = p.createBid();
        
        bid.setFemaleP(Double.parseDouble(femalejTextField1.getText()));
        bid.setMaleP(Double.parseDouble(malejTextField2.getText()));
        
        bid.setPschP(Double.parseDouble(primarySchooljTextField3.getText()));
        bid.setHschP(Double.parseDouble(highSchooljTextField4.getText()));
        bid.setBechP(Double.parseDouble(bachelorjTextField5.getText()));
        bid.setMasterP(Double.parseDouble(masterTextField6.getText()));
        bid.setPhdP(Double.parseDouble(phdjTextField7.getText()));
        
        bid.setNeP(Double.parseDouble(nejTextField1.getText()));
        bid.setNwp(Double.parseDouble(nwjTextField3.getText()));
        bid.setSeP(Double.parseDouble(sejTextField2.getText()));
        bid.setSwP(Double.parseDouble(swJTextField4.getText()));
        
        bid.setBigP(Double.parseDouble(bigjTextField5.getText()));
        bid.setSmallP(Double.parseDouble(smalljTextField6.getText()));
        
        bid.setUlP(Double.parseDouble(uljTextField7.getText()));
        bid.setUrP(Double.parseDouble(urjTextField9.getText()));
        bid.setBlP(Double.parseDouble(bljTextField10.getText()));
        bid.setBrP(Double.parseDouble(brjTextField8.getText()));
        
    }//GEN-LAST:event_createRulejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bachelorjTextField5;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bigjTextField5;
    private javax.swing.JTextField bljTextField10;
    private javax.swing.JTextField brjTextField8;
    private javax.swing.JButton createRulejButton;
    private javax.swing.JTextField femalejTextField1;
    private javax.swing.JTextField highSchooljTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField malejTextField2;
    private javax.swing.JTextField masterTextField6;
    private javax.swing.JTextField nejTextField1;
    private javax.swing.JTextField nwjTextField3;
    private javax.swing.JTextField phdjTextField7;
    private javax.swing.JTextField primarySchooljTextField3;
    private javax.swing.JTextField productCompanyjTextField;
    private javax.swing.JTextField productCompanyjTextField1;
    private javax.swing.JComboBox productjComboBox6;
    private javax.swing.JTextField sejTextField2;
    private javax.swing.JTextField smalljTextField6;
    private javax.swing.JTextField swJTextField4;
    private javax.swing.JTextField uljTextField7;
    private javax.swing.JTextField urjTextField9;
    private javax.swing.JButton viewjButton6;
    // End of variables declaration//GEN-END:variables
}
