/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminProductCompany;

import Business.Enterprise.Adpublisher.AdSpace;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany.Product;
import Business.Enterprise.ProductCompanyEnterprise;
import Business.UserAccount.Viewer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anna
 */
public class OldManageBidRuleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OldManageBidRuleJPanel
     */
    private JPanel userProcessContainer;
    private ProductCompanyEnterprise productCompanyEnterprise;
    //private Product product;
    public OldManageBidRuleJPanel(JPanel userProcessContainer, ProductCompanyEnterprise productCompanyEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productCompanyEnterprise = productCompanyEnterprise;
        pooProductCom();
        popCom();
        
    }

    //Product product= (Product) productjComboBox6.getSelectedItem();
     public void pooProductCom(){
     productjComboBox6.removeAllItems();
     for (Product p: productCompanyEnterprise.getProductCatalog().getProductcatalog()){
         productjComboBox6.addItem(p);
     }   
    }
     
     public void popCom(){
         viewerGenderjComboBox1.removeAllItems();
     for (Viewer.GenderType type : Viewer.GenderType.values()){
         viewerGenderjComboBox1.addItem(type);
     } 
     
     viewerLocationjComboBox3.removeAllItems();
     for (Viewer.LocationType type : Viewer.LocationType.values()){
         viewerLocationjComboBox3.addItem(type);
     }
     
     viewerEducationjComboBox2.removeAllItems();
     for (Viewer.EducationType type : Viewer.EducationType.values()){
         viewerEducationjComboBox2.addItem(type);
     }
     
     adSpaceSizejComboBox4.removeAllItems();
     for (AdSpace.SizeType stype : AdSpace.SizeType.values()){
         adSpaceSizejComboBox4.addItem(stype);
     } 
     adSpaceLocationjComboBox5.removeAllItems();
     for(AdSpace.LocationType ltype: AdSpace.LocationType.values()){
         adSpaceLocationjComboBox5.addItem(ltype);
     } 
     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        productCompanyjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productCompanyjTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewerGenderjComboBox1 = new javax.swing.JComboBox();
        viewerEducationjComboBox2 = new javax.swing.JComboBox();
        viewerLocationjComboBox3 = new javax.swing.JComboBox();
        viewerGenderjTextField1 = new javax.swing.JTextField();
        viewerEducationjTextField2 = new javax.swing.JTextField();
        viewerLocationjTextField3 = new javax.swing.JTextField();
        submitGenderjButton1 = new javax.swing.JButton();
        submitEducationjButton2 = new javax.swing.JButton();
        submitLocationViewerjButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        adSpaceSizejComboBox4 = new javax.swing.JComboBox();
        adSpaceSizejTextField4 = new javax.swing.JTextField();
        submitSizejButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        submitLocationAdSpacejButton5 = new javax.swing.JButton();
        adSpaceLocationjComboBox5 = new javax.swing.JComboBox();
        adSpaceLocationjTextField5 = new javax.swing.JTextField();
        viewjButton6 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        productjComboBox6 = new javax.swing.JComboBox();

        jLabel2.setText("Product Company");

        jLabel3.setText("Product Company");

        jLabel1.setText("Bid RULE setting");

        jLabel4.setText("Viewer Gender Type");

        jLabel5.setText("Viewer Education Type");

        jLabel6.setText("Viewer Location Type");

        viewerGenderjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        viewerEducationjComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        viewerLocationjComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitGenderjButton1.setText("Submit");

        submitEducationjButton2.setText("Submit ");

        submitLocationViewerjButton3.setText("Submit");

        jLabel7.setText("Ad Space Size Type");

        adSpaceSizejComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitSizejButton4.setText("Submit");

        jLabel8.setText("Ad Space Location Type");

        submitLocationAdSpacejButton5.setText("Submit");

        adSpaceLocationjComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        viewjButton6.setText("View Bid RULE");
        viewjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButton6ActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Product ");

        productjComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(43, 43, 43)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(adSpaceLocationjComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(adSpaceLocationjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(46, 46, 46)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(submitGenderjButton1)
                            .add(submitEducationjButton2)
                            .add(submitSizejButton4)
                            .add(submitLocationAdSpacejButton5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, submitLocationViewerjButton3))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel9)
                                .add(31, 31, 31)
                                .add(productjComboBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(layout.createSequentialGroup()
                                    .add(jLabel4)
                                    .add(34, 34, 34)
                                    .add(viewerGenderjComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(viewerGenderjTextField1))
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel5)
                                        .add(jLabel6)
                                        .add(jLabel7))
                                    .add(18, 18, 18)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(viewerEducationjComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(viewerEducationjTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(adSpaceSizejComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(viewerLocationjComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(viewerLocationjTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                .add(adSpaceSizejTextField4)))))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(viewjButton6)
                        .add(158, 158, 158))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .add(114, 114, 114)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(productCompanyjTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(backJButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(productCompanyjTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(3, 3, 3)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(productjComboBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(viewjButton6))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(viewerGenderjComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(viewerGenderjTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(submitGenderjButton1))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(55, 55, 55)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(viewerEducationjComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(viewerEducationjTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(45, 45, 45)
                        .add(submitEducationjButton2)))
                .add(50, 50, 50)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(viewerLocationjComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(viewerLocationjTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(submitLocationViewerjButton3))
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(adSpaceSizejComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(adSpaceSizejTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(submitSizejButton4))
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(submitLocationAdSpacejButton5)
                    .add(adSpaceLocationjComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(adSpaceLocationjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 53, Short.MAX_VALUE)
                .add(backJButton)
                .add(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewjButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adSpaceLocationjComboBox5;
    private javax.swing.JTextField adSpaceLocationjTextField5;
    private javax.swing.JComboBox adSpaceSizejComboBox4;
    private javax.swing.JTextField adSpaceSizejTextField4;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField productCompanyjTextField;
    private javax.swing.JTextField productCompanyjTextField1;
    private javax.swing.JComboBox productjComboBox6;
    private javax.swing.JButton submitEducationjButton2;
    private javax.swing.JButton submitGenderjButton1;
    private javax.swing.JButton submitLocationAdSpacejButton5;
    private javax.swing.JButton submitLocationViewerjButton3;
    private javax.swing.JButton submitSizejButton4;
    private javax.swing.JComboBox viewerEducationjComboBox2;
    private javax.swing.JTextField viewerEducationjTextField2;
    private javax.swing.JComboBox viewerGenderjComboBox1;
    private javax.swing.JTextField viewerGenderjTextField1;
    private javax.swing.JComboBox viewerLocationjComboBox3;
    private javax.swing.JTextField viewerLocationjTextField3;
    private javax.swing.JButton viewjButton6;
    // End of variables declaration//GEN-END:variables
}
