/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ViewerRole;

import Business.EcoSystem;
import Business.Enterprise.AdPublisherEnterprise;
import Business.Enterprise.Adpublisher.AdSpace;
import Business.Enterprise.Adpublisher.AdSpaceList;
import Business.Enterprise.ProductCompany.Product;
import Business.UserAccount.Auction;
import Business.UserAccount.Viewer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anna
 */
public class ViewAdPublisherJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdPublisherJPanel
     */
   JPanel userProcessContainer;
   EcoSystem system;
   AdPublisherEnterprise adPublisherEnterprise;
   Viewer viewer;
   Product product;
   //AdSpace adSpace;
   AdSpaceList adSpaceList;
   Auction auction;
    public ViewAdPublisherJPanel(JPanel userProcessContainer, EcoSystem system, 
            AdPublisherEnterprise ape,Viewer viewer, Product product,AdSpaceList adSpaceList, Auction auction) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.adPublisherEnterprise = ape;
        this.viewer = viewer;
        this.product = product;
        //this.adSpace = adSpace;
        this.adSpaceList = adSpaceList;
        this.auction = auction;
        
        publisherjTextField.setText(adPublisherEnterprise.getName());
        displayProductAd(product, adSpaceList);
    }
    
    
    public void displayProductAd(Product product, AdSpaceList adSpaceList){
       for (AdSpace adSpace : adSpaceList.getAdSpaceList()){
        if (adSpace.getSizeType().equals(AdSpace.SizeType.Big) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.UpRight)){
            urBigjLabel4.setText(product.getName());
        }
         if (adSpace.getSizeType().equals(AdSpace.SizeType.Big) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.UpLeft)){
            ulBigjLabel2.setText(product.getName());
        }
         else if (adSpace.getSizeType().equals(AdSpace.SizeType.Small) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.UpRight)){
            urSmalljLabel3.setText(product.getName());
        }
         else if (adSpace.getSizeType().equals(AdSpace.SizeType.Small) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.UpLeft)){
            ulSmalljLabel1.setText(product.getName());
        }
           else if (adSpace.getSizeType().equals(AdSpace.SizeType.Big) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.BelowLeft)){
            blBigjLabel6.setText(product.getName());
        }
           else if (adSpace.getSizeType().equals(AdSpace.SizeType.Big) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.BelowRight)){
            brBigjLabel8.setText(product.getName());
        }
           else if (adSpace.getSizeType().equals(AdSpace.SizeType.Small) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.BelowLeft)){
            blSmalljLabel5.setText(product.getName());
        }
           else  if (adSpace.getSizeType().equals(AdSpace.SizeType.Small) && 
                adSpace.getLocationType().equals(AdSpace.LocationType.BelowRight)){
            brSmalljLabel7.setText(product.getName());
        }   
       }
        
          
          
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        publisherjTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        ulSmalljLabel1 = new javax.swing.JLabel();
        ulBigjLabel2 = new javax.swing.JLabel();
        blSmalljLabel5 = new javax.swing.JLabel();
        blBigjLabel6 = new javax.swing.JLabel();
        urSmalljLabel3 = new javax.swing.JLabel();
        urBigjLabel4 = new javax.swing.JLabel();
        brSmalljLabel7 = new javax.swing.JLabel();
        brBigjLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("You are viewing:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));
        add(publisherjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        add(ulSmalljLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 20));

        ulBigjLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(ulBigjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 50));
        add(blSmalljLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 30));

        blBigjLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(blBigjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 120, 50));
        add(urSmalljLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 110, 20));

        urBigjLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(urBigjLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 110, 50));
        add(brSmalljLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 100, 30));

        brBigjLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(brBigjLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 130, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel blBigjLabel6;
    private javax.swing.JLabel blSmalljLabel5;
    private javax.swing.JLabel brBigjLabel8;
    private javax.swing.JLabel brSmalljLabel7;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField publisherjTextField;
    private javax.swing.JLabel ulBigjLabel2;
    private javax.swing.JLabel ulSmalljLabel1;
    private javax.swing.JLabel urBigjLabel4;
    private javax.swing.JLabel urSmalljLabel3;
    // End of variables declaration//GEN-END:variables
}
