/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ViewerRole;

import Business.EcoSystem;
import Business.Enterprise.AdPublisherEnterprise;
import Business.Enterprise.Adpublisher.AdSpace;
import Business.Enterprise.Adpublisher.AdSpaceList;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProductCompany.Bid;
import Business.Enterprise.ProductCompany.Product;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.Auction;
import Business.UserAccount.UserAccount;
import Business.UserAccount.Viewer;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anna
 */
public class ViewerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    Viewer viewer;
    //Enterprise enterprise;
    /**
     * Creates new form ViewerWorkAreaJPanel
     */
    public ViewerWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.viewer = (Viewer) user;
        
        popData();    
        
    }

     public void popData() {

        DefaultTableModel model = (DefaultTableModel) adPublisherJTable.getModel();

        model.setRowCount(0);

        for (Network network : system.getNetworkList()){
            for (Enterprise ape : network.getEnterpriseDirectory().getEnterpriseList()){
                if (ape instanceof AdPublisherEnterprise){
                Object row[] = new Object[1];
                row[0] = ape;
               
                ((DefaultTableModel) adPublisherJTable.getModel()).addRow(row);
                }
            }
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adPublisherJTable = new javax.swing.JTable();
        goWebsitejButton1 = new javax.swing.JButton();
        searchjTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("My Work Area - Viewer Role");

        adPublisherJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad Publisher Name"
            }
        ));
        jScrollPane1.setViewportView(adPublisherJTable);

        goWebsitejButton1.setText("Go to Website");
        goWebsitejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goWebsitejButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(31, 31, 31)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(47, 47, 47)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(layout.createSequentialGroup()
                                    .add(searchjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(66, 66, 66)
                                    .add(jButton2))
                                .add(jLabel2))))
                    .add(goWebsitejButton1))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel2)
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2))
                .add(29, 29, 29)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(goWebsitejButton1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goWebsitejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goWebsitejButton1ActionPerformed
        // TODO add your handling code here:
        
                
        int selectedRow = adPublisherJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        AdPublisherEnterprise ape = (AdPublisherEnterprise) adPublisherJTable.getValueAt(selectedRow, 0);

        Product inProduct = new Product();
        inProduct.setBid(new Bid());
        AdSpace inAdSpace = null;
        AdSpaceList adSpaceList = new AdSpaceList();
        Auction auction = new Auction();
        
        
        for (AdSpace adSpace : ape.getAdSpaceList().getAdSpaceList()){
       // get winner product;
         auction = viewer.getAuctionDirectory().
                 createAuctionandFindWinnerProduct(system, viewer, adSpace);
         auction.setTheAdPublisherEnterprise(ape);
         
         Product winnerProduct = auction.getWinnerProduct();
          if(inProduct.getBid().getBidPrice() <= winnerProduct.getBid().getBidPrice() ){
              inProduct = winnerProduct;
              inAdSpace = adSpace;
              adSpaceList.add(adSpace);
              ape.setAdSpaceList(adSpaceList);
          }   
        }
        
       
        
        
        ViewAdPublisherJPanel vapJ = new ViewAdPublisherJPanel(userProcessContainer,system,
                ape,viewer,inProduct,adSpaceList,auction);
         userProcessContainer.add("processWorkRequestJPanel", vapJ);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_goWebsitejButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adPublisherJTable;
    private javax.swing.JButton goWebsitejButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchjTextField;
    // End of variables declaration//GEN-END:variables
}
