/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.UserAccount.Auction;
import Business.UserAccount.Viewer;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anna
 */
public class ManageAuctionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAuctionJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageAuctionJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        popAuctionTable();
    }

    public void popAuctionTable(){
        DefaultTableModel model = (DefaultTableModel) auctionjTable1.getModel();
        model.setRowCount(0);
        //for (Viewer viewer : system.getViewerList()){
        if (system.getUserAccountDirectory().getViewerList() == null){
        
        }else{   
        for (Viewer viewer : system.getUserAccountDirectory().getViewerList()){  
              if (viewer.getAuctionDirectory().getAuctionDirectory() == null){
        
           }else{
                  for (Auction a : viewer.getAuctionDirectory().getAuctionDirectory()){
            
               Object row[] = new Object[6];
                row[0] = a;
                row[1] = viewer;
                row[2] = a.getWinnerProduct();
                
                row[3] = a.getWinnerProduct().getBid();
                row[4] = a.getWinnerProduct().getBid().getBidPrice();
                
                row[5] = a.getTheadSpace();
//                row[5] = viewer.getAge();
//                row[6] = viewer.getAddress();
//                row[7] = viewer.getZipCode();
//                row[8] = viewer.getLocation();
                ((DefaultTableModel) auctionjTable1.getModel()).addRow(row);
                  }
        }
        }
        }   
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        auctionjTable1 = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        jLabel1.setText("View Auction History");

        auctionjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Auction ID", "Viewer", "Winner Product", "Bid ", "Bid Price", "Ad Space"
            }
        ));
        jScrollPane1.setViewportView(auctionjTable1);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(backJButton))
                    .add(layout.createSequentialGroup()
                        .add(209, 209, 209)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(58, 58, 58)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 635, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jLabel1)
                .add(33, 33, 33)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 124, Short.MAX_VALUE)
                .add(backJButton)
                .add(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auctionjTable1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
